name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint
      run: npm run lint
    
    - name: Install Playwright
      run: npx playwright install --with-deps chromium
    
    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg
    
    - name: Run Smoke Tests
      run: npm run test:smoke
    
    - name: Run Unit Tests
      run: npm run test:unit
    
    - name: Run Integration Tests (with mocks)
      run: npm run test:integration
    
    - name: Run E2E Tests
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: npm run test:e2e
    
    - name: Test Pattern Generation
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        # Create a simple test script
        cat > test-pattern.js << 'EOF'
        import { dazzle } from './src/dazzle.js';
        
        try {
          const pattern = await dazzle('test.mp3', 'Test Artist', 'Test Song');
          console.log('Pattern generated successfully');
          process.exit(0);
        } catch (error) {
          console.error('Pattern generation failed:', error);
          process.exit(1);
        }
        EOF
        
        # Run the test
        timeout 60s node test-pattern.js
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          test-results/
          recordings/
        retention-days: 7